-- Esquema reproducible de Falta Uno. Ya fue aplicado manualmente en el proyecto inicial.
begin;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  first_name text not null, last_name text not null,
  category text not null check (category in ('7ma','6ta','5ta','4ta','3ra','2da','1ra')),
  gender text not null check (gender in ('masculino','femenino')),
  playing_position text not null check (playing_position in ('drive','reves')),
  location text, latitude double precision, longitude double precision,
  search_mode text not null default 'radius' check (search_mode in ('radius','place')),
  search_radius_km integer not null default 20 check (search_radius_km between 1 and 100),
  preferred_place text, avatar_path text, created_at timestamptz not null default now()
);

create table if not exists public.profile_private (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  phone text not null unique, created_at timestamptz not null default now()
);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  creator_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check (char_length(title) between 3 and 70),
  visibility text not null check (visibility in ('open','private')),
  match_date date not null, match_time time not null, club text not null, location text,
  latitude double precision, longitude double precision,
  category text not null check (category in ('7ma','6ta','5ta','4ta','3ra','2da','1ra')),
  match_format text not null default 'standard' check (match_format in ('standard','mixed')),
  private_password_hash text, max_players integer not null default 4 check (max_players = 4),
  status text not null default 'open' check (status in ('open','full','cancelled')),
  created_at timestamptz not null default now()
);

create table if not exists public.match_participants (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  player_id uuid not null references public.profiles(id) on delete cascade,
  participant_status text not null default 'confirmed' check (participant_status in ('invited','confirmed','declined')),
  team integer check (team in (1,2)), created_at timestamptz not null default now(), unique (match_id, player_id)
);

create unique index if not exists one_active_match_per_creator on public.matches (creator_id) where status in ('open','full');
create index if not exists matches_date_time_index on public.matches (match_date, match_time);
create index if not exists matches_visibility_status_index on public.matches (visibility, status);
create index if not exists participants_player_index on public.match_participants (player_id);
create index if not exists participants_match_index on public.match_participants (match_id);

alter table public.profiles enable row level security;
alter table public.profile_private enable row level security;
alter table public.matches enable row level security;
alter table public.match_participants enable row level security;

drop policy if exists "Jugadores registrados pueden ver perfiles" on public.profiles;
drop policy if exists "Cada usuario crea su perfil" on public.profiles;
drop policy if exists "Cada usuario modifica su perfil" on public.profiles;
drop policy if exists "Cada usuario elimina su perfil" on public.profiles;
create policy "Jugadores registrados pueden ver perfiles" on public.profiles for select to authenticated using (true);
create policy "Cada usuario crea su perfil" on public.profiles for insert to authenticated with check (auth.uid() = id);
create policy "Cada usuario modifica su perfil" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);
create policy "Cada usuario elimina su perfil" on public.profiles for delete to authenticated using (auth.uid() = id);

drop policy if exists "Cada usuario ve sus datos privados" on public.profile_private;
drop policy if exists "Cada usuario crea sus datos privados" on public.profile_private;
drop policy if exists "Cada usuario modifica sus datos privados" on public.profile_private;
drop policy if exists "Cada usuario elimina sus datos privados" on public.profile_private;
create policy "Cada usuario ve sus datos privados" on public.profile_private for select to authenticated using (auth.uid() = user_id);
create policy "Cada usuario crea sus datos privados" on public.profile_private for insert to authenticated with check (auth.uid() = user_id);
create policy "Cada usuario modifica sus datos privados" on public.profile_private for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Cada usuario elimina sus datos privados" on public.profile_private for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "Usuarios pueden ver partidos permitidos" on public.matches;
drop policy if exists "Usuarios crean sus propios partidos" on public.matches;
drop policy if exists "Organizador modifica su partido" on public.matches;
drop policy if exists "Organizador elimina su partido" on public.matches;
create policy "Usuarios pueden ver partidos permitidos" on public.matches for select to authenticated using (
  visibility = 'open' or creator_id = auth.uid() or exists (
    select 1 from public.match_participants where match_id = matches.id and player_id = auth.uid()
  )
);
create policy "Usuarios crean sus propios partidos" on public.matches for insert to authenticated with check (creator_id = auth.uid());
create policy "Organizador modifica su partido" on public.matches for update to authenticated using (creator_id = auth.uid()) with check (creator_id = auth.uid());
create policy "Organizador elimina su partido" on public.matches for delete to authenticated using (creator_id = auth.uid());

drop policy if exists "Jugador ve sus participaciones" on public.match_participants;
create policy "Jugador ve sus participaciones" on public.match_participants for select to authenticated using (player_id = auth.uid());

drop policy if exists "Usuarios registrados ven avatares" on storage.objects;
drop policy if exists "Usuario sube su avatar" on storage.objects;
drop policy if exists "Usuario modifica su avatar" on storage.objects;
drop policy if exists "Usuario elimina su avatar" on storage.objects;
create policy "Usuarios registrados ven avatares" on storage.objects for select to authenticated using (bucket_id = 'avatars');
create policy "Usuario sube su avatar" on storage.objects for insert to authenticated with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "Usuario modifica su avatar" on storage.objects for update to authenticated using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text) with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "Usuario elimina su avatar" on storage.objects for delete to authenticated using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

commit;

create extension if not exists pg_cron;
create or replace function public.delete_started_matches() returns void language plpgsql security definer set search_path = public as $$
begin
  delete from public.matches where status in ('open','full')
    and ((match_date + match_time) at time zone 'America/Argentina/Buenos_Aires') <= now();
end;
$$;
revoke all on function public.delete_started_matches() from public, anon, authenticated;
select cron.unschedule(jobid) from cron.job where jobname = 'delete-started-matches';
select cron.schedule('delete-started-matches', '* * * * *', $$select public.delete_started_matches();$$);
